# Generated by Django 4.0.4 on 2022-06-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
    ]
