# Generated by Django 4.0.4 on 2022-06-16 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_remove_userprofile_gender_remove_userprofile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
    ]
